### ISSUE TITLE
after i choose  the permissions i want nothing happens after i presss the submit button

### ISSUE THREAD

**Issue by Abdallah504** [AmitXShukla/Flutter-MYSQL-CRM-app#2]

**Comment by Abdallah504** [comment]
![image](https://user-images.githubusercontent.com/53866723/159550725-e1a5d304-ef9f-4c7c-bd61-641134a53f38.png)

**Comment by AmitXShukla** [comment]
please try updating Permissions, click on Generate Access token and then click on submit, 
Also, pay attention to debug info. Often it depends on User Objects and permissions.
![image](https://user-images.githubusercontent.com/20031132/159556128-bceb1ecb-4b93-48cd-9769-ab9b45151d35.png)
![image](https://user-images.githubusercontent.com/20031132/159556149-8867b540-74ef-4fa6-816a-2a147840a01b.png)
